name: sizing
description: A new Flutter package.
version: 1.0.0
homepage: https://github.com/liontude/sizing

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter